services:

    fastapi:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fastapi
        command: >
            bash -c "alembic upgrade head && pytest && fastapi run app/main.py --port 8000"
        environment:
            DATABASE_URL: ${DATABASE_URL}
            JWT_SECRET: ${JWT_SECRET}
            JWT_ALGORITHM: ${JWT_ALGORITHM}
            JWT_EXPIRATION: ${JWT_EXPIRATION}
            TIMEZONE: ${TIMEZONE}
        restart: always
        ports:
            - "8000:8000"
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        container_name: postgres
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        ports:
            - "5432:5432"
#         volumes:
#             - postgres-data:/var/lib/postgresql/data

# volumes:
#     postgres-data: